// Auto-generated file
// This code was generated by scripts from the Glimpse.Client repository.
// Changes to this file will be lost when the code is regenerated. If you want 
// to improve this file, do the modification on the Glimpse.Client repo and 
// send a pull-request from there.